### PR TITLE
jellyshot: add PORT variable to configuration

### PR DESCRIPTION
**Pull request by alyptik**
Signed-off-by: Joey Pabalinas <joeypabalinas@gmail.com>

### CODE REVIEW

**Comment by jelly** [comment]
Please add a commented out PORT option to the 'config.example'

**Comment by alyptik** [comment]
The other examples aren't commented out in that file, do you still want it commented or just have them matching (not commented but add information to the explanation comment)?

e.g.
```bash
SERVER='server.domain'
PORT='2222'
SERVER_PATH=''
# Becomes: https://server.domain:2222/tmp/<name>
SUFFIX='tmp'
# SSH user
USER='user'
```

**Comment by jelly** [comment]
Hmm, well I assume most people use ssh at port 22, so that's why I opted for commenting it out.

**Comment by alyptik** [comment]
Well how's this:

```bash

SERVER='server.domain'
PORT='22'
SERVER_PATH=''
# Becomes: `scp -P 22 <filename> https://server.domain/tmp/<name>`
SUFFIX='tmp'
# SSH user
USER='user'
```

I feel like this would be a decent explanation since it's how the port is actually used in the code.

**Pull request merged**
